name: MarianiWitabora
favicon: null
layout_spectrum: 0.409501314163208
typography_spectrum: 0.319708518916741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#554e4b'
    - '#797677'
    - '#bcb6b7'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
